services:

  hero-certificates:
      build:
        context: ./app
      hostname: certifs
      container_name: hero-certificates
      read_only: false
      restart: unless-stopped
      ports:
        - 80:80
      environment:
        - LISTEN_PORT=80
      deploy:
        resources:
          limits:
            cpus: 0.5
            memory: 512M