services:

  certificates_nginx:
    image: nginx:alpine
    container_name: certificates_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "443:443"
    mem_limit: 512m
    cpus: 1
    read_only: false
    networks:
      - certificates_net

  certificates_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: certificates_app
    restart: unless-stopped
    mem_limit: 1G
    cpus: 1
    read_only: false
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - LISTEN_PORT=5000
    networks:
      - certificates_net

networks:
  certificates_net:
    driver: bridge
